# Generated by Django 5.1.7 on 2025-03-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
